---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflare.fullname" . }}
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudflare.fullname" . }}-cb
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflare.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
