---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare.fullname" . }}
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
    app: cloudflare
spec:
  selector:
    app: cloudflare
  ports:
    - name: cf-tun-metrics
      protocol: TCP
      port: 2000
      targetPort: cf-tun-metrics
